spring:
  datasource:
    url: jdbc:mysql://db:3306/ecommerce?useSSL=true&serverTimezone=Asia/Bangkok
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

app:
  cors:
    enabled: false
    allowed-origin: *
  file:
    upload-dir: ${user.dir}/uploads
  frontend-url: https://intproj24.sit.kmutt.ac.th/ssa1
  backend-url: https://intproj24.sit.kmutt.ac.th/ssa1
