spring:
  datasource:
    url: jdbc:mysql://db:3306/ecommerce?useSSL=true&serverTimezone=Asia/Bangkok
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

app:
  cors:
    enabled: false
    allowed-origin: http://ip24ssa1.sit.kmutt.ac.th,http://intproj24.sit.kmutt.ac.th
  file:
    upload-dir: ${user.dir}/uploads